### ISSUE TITLE
Whatsapp Profile

### ISSUE THREAD

**Issue by adornodev** [jonathanferreiras/whats-bot#1]
Boa noite, Jonathan.
Primeiramente, parabéns pelo o seu projeto. Muito bem explicado.
Quando fui analisar melhor o código, vi que faz uso do profile do whatsapp. Como é esse arquivo? Aonde posso consegui-lo?

**Comment by jonathanferreiras** [comment]
Bom dia Lucas,

Agradeço o carinho e peço deculpas pela demora.

O profile serve para não precisar logar no WhatsApp toda vez que o bot iniciar.
Você ira fazer o procedimento do QRCode apenas uma vez e ficará salva quando iniciar o bot outras vezes.

**Comment by 191104305** [comment]
Boa noite, Jonathan. Cara você é muito inteligente pra fazer esse robô, mas eu sou o contrário, nem consegui rodar ele. Aparece várias mensagens de erro quando tento rodar. Já instalei o requirements, coloquei o driver do selenium na pasta indicada, mas sempre da erro. Cara eu passei um dia inteiro e a a madrugada tentando descobrir onde eu estava errando, vc nem imagina a depressão que isso me causou. Mas deixando isso de lado. Teria uma dica ai pra mim conseguir rodar ele de primeira?
Um abraço!

**Comment by jonathanferreiras** [comment]
Boa noite Diego,
Agradeço os elogios :)

Vamos lá, você chegou a ver artigo que eu fiz mostrando como foi realizado? Caso ainda não tenha visto, ele pode te ajudar. Acesse : ChatBot no WhatsApp com Python
https://www.linkedin.com/pulse/chatbot-whatsapp-com-python-jonathan-ferreira
Caso ainda tenha dúvidas ou problemas ao rodar o aplicativo, fico a disposição a te ajudar no que for necessário. Só me chamar lá no linkedin ;)

No mais, não se incomode caso ocorra erros que não consiga resolver. O importante é apenas não desistirmos. 

Grande abraço
