### ISSUE TITLE
Trocas

### ISSUE THREAD

**Issue by luxu** [jonathanferreiras/whats-bot#3]
### mas pra q serve akela linha?

**Comment by jonathanferreiras** [comment]
Boa noite Luciano,

Acredito que já tenhas resolvido o problema. 
Caso ainda tenha dúvidas:

A linha
webdriver.Chrome(self.chrome, chrome_options=self.options)
Serve para iniciar o chrome com as configurações que colocamos. No caso com nosso profile.

A linha 
self.chrome = self.dir_path+'\chromedriver.exe'
Serve para carregar o driver do chrome em nossa aplicação.

Valeu!
